baseURL = 'https://pakkudon.github.io/blog/'
languageCode = 'en-au'
title = "PakkuDon's blog"
theme = 'hugo-theme-stack'

# Stack theme-specific configuration
[params]
  [params.sidebar]
  emoji = "ðŸ¦ˆ"
  subtitle = "Software Engineer"

    [params.sidebar.avatar]
    enabled = true
    local = false
    src = "https://avatars.githubusercontent.com/u/5287128"

  [params.footer]
    since = "2023"
