baseURL = 'https://pakkudon.github.io/blog/'
languageCode = 'en-au'
title = "PakkuDon's blog"
theme = 'hugo-theme-stack'

[permalinks]
  post = '/post/:year/:month/:day/:title/'
  link = '/link/:year/:month/:day/:title/'

# Stack theme-specific configuration
[params]
  mainSections = ['post', 'link']

  [params.sidebar]
  emoji = "ðŸ¦ˆ"
  subtitle = "Software Engineer"

    [params.sidebar.avatar]
    enabled = true
    local = false
    src = "https://avatars.githubusercontent.com/u/5287128"

  [params.footer]
    since = "2023"

  [params.widgets]
    [[params.widgets.page]]
      type = "toc"


[menu]
  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/PakkuDon"

    [menu.social.params]
    icon = "brand-github"

  [[menu.social]]
  identifier = "portfolio"
  name = "Portfolio"
  url = "https://pakkudon.github.io/"

    [menu.social.params]
    icon = "link"

  [[menu.social]]
  identifier = "rss"
  name = "RSS Feed"
  url = "/index.xml"

    [menu.social.params]
    icon = "rss"

